#ifndef CNC_HAL_RESET_H
#define CNC_HAL_RESET_H
#ifdef __cplusplus
extern "C"
{
#endif

#undef ENABLE_COOLANT
#undef ENABLE_WIFI
#undef ENABLE_BLUETOOTH
#undef ENABLE_SKEW_COMPENSATION
#undef SKEW_COMPENSATION_XY_ONLY
#undef ENABLE_LINACT_PLANNER
#undef ENABLE_LINACT_COLD_START
#undef ENABLE_BACKLASH_COMPENSATION
#undef BRESENHAM_16BIT
#undef ENABLE_EXTRA_SYSTEM_CMDS
#undef RAM_ONLY_SETTINGS
#undef FORCE_SOFT_POLLING
#undef STATUS_AUTOMATIC_REPORT_INTERVAL_ENABLE
#undef DISABLE_ALL_CONTROLS
#undef ESTOP_PULLUP_ENABLE
#undef SAFETY_DOOR_PULLUP_ENABLE
#undef FHOLD_PULLUP_ENABLE
#undef CS_RES_PULLUP_ENABLE
#undef DISABLE_ALL_LIMITS
#undef LIMIT_X_DISABLE
#undef LIMIT_Y_DISABLE
#undef LIMIT_X2_DISABLE
#undef LIMIT_Y2_DISABLE
#undef LIMIT_X_PULLUP_ENABLE
#undef LIMIT_Y_PULLUP_ENABLE
#undef LIMIT_X2_PULLUP_ENABLE
#undef LIMIT_Y2_PULLUP_ENABLE
#undef DISABLE_PROBE
#undef PROBE_PULLUP_ENABLE
#undef ENABLE_MULTI_STEPPER_AXIS
#undef TOOL1
#undef PEN_SERVO_PWM
#undef PEN_SERVO_PWM_DIR
#undef ENABLE_LASER_PPI
#undef SOFT_SPI_CLK
#undef SOFT_SPI_SDO
#undef SOFT_SPI_SDI
#undef IC74HC595_COUNT
#undef ENCODERS
#undef ENABLE_MAIN_LOOP_MODULES
#undef ENABLE_IO_MODULES
//#undef ENABLE_PARSER_MODULES
#undef ENABLE_MOTION_CONTROL_MODULES
#undef ENABLE_RT_SYNC_MOTIONS
#undef DISABLE_SETTINGS_MODULES

#ifdef __cplusplus
}
#endif
#endif
